### ISSUE TITLE
Cannot read property 'block_id' of undefined

### ISSUE THREAD

**Issue by lacabra** [forbole/big-dipper#278]
**Describe the bug**
I start the explorer as per the instructions, and everything seems to be well configured, but when looking at the logs I see this error repeatedly:
```
I20200211-00:07:15.578(0)? http://172.31.41.58:26657/block?height=1
I20200211-00:07:15.582(0)? TypeError: Cannot read property 'block_id' of undefined
I20200211-00:07:15.582(0)?     at MethodInvocation.blocks.blocksUpdate (imports/api/blocks/server/methods.js:194:59)
I20200211-00:07:15.582(0)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20200211-00:07:15.582(0)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1689:15)
I20200211-00:07:15.583(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20200211-00:07:15.583(0)?     at resolve (packages/ddp-server/livedata_server.js:1687:36)
I20200211-00:07:15.583(0)?     at new Promise (<anonymous>)
I20200211-00:07:15.583(0)?     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
I20200211-00:07:15.583(0)?     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
I20200211-00:07:15.583(0)?     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
I20200211-00:07:15.584(0)?     at updateBlock (server/main.js:36:12)
I20200211-00:07:15.584(0)?     at server/main.js:193:21
I20200211-00:07:15.584(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20200211-00:07:15.584(0)?     at packages/meteor.js:550:25
I20200211-00:07:15.584(0)?     at runWithEnvironment (packages/meteor.js:1286:24)
```

**To Reproduce**
1. Follow the instructions on the README:
```
meteor npm install
meteor update
meteor --settings settings.json
```

**Expected behavior**
The block explorer should run without errors

**Screenshots**
This is what the block explorer looks like:

![screenshot](https://user-images.githubusercontent.com/6098973/74202149-dee25880-4c28-11ea-8e58-dc1cc0d75f03.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Brave
 - Cosmos/Gaia `v2.0.6`

**Comment by kwunyeung** [comment]
Hi @lacabra ! Thanks for trying out Big Dipper!

May I know if your LCD (rest server) is running properly as well? I haven't tested it out with `gaia v2.0.6` with a fresh start. I will try and see what is happening with you.

**Comment by lacabra** [comment]
Thanks @kwunyeung for your prompt response. Yes, the rest server seems to be running fine. It responds with a `200` HTTP code to all requests it gets. For example, from the following output, one of these requests resulted in the error above (I cannot tell which one):

```
gaiacli rest-server --laddr tcp://172.31.41.58:1317 --node tcp://172.31.41.58:26657
I[2020-02-11|04:39:16.244] Starting application REST service (chain-id: "network-testnet")... module=rest-server 
I[2020-02-11|04:39:16.244] Starting RPC HTTP server on 172.31.41.58:1317 module=rest-server 
I[2020-02-11|04:39:16.710] Served RPC HTTP response                     module=rest-server method=GET url=/gov/proposals status=200 duration=1 remoteAddr=172.31.32.247:59070
I[2020-02-11|04:39:21.606] Served RPC HTTP response                     module=rest-server method=GET url=/staking/validators status=200 duration=2 remoteAddr=172.31.32.247:59088
I[2020-02-11|04:39:21.610] Served RPC HTTP response                     module=rest-server method=GET url=/staking/pool status=200 duration=0 remoteAddr=172.31.32.247:59090
I[2020-02-11|04:39:21.613] Served RPC HTTP response                     module=rest-server method=GET url="/staking/validators?status=unbonding" status=200 duration=1 remoteAddr=172.31.32.247:59092
I[2020-02-11|04:39:21.618] Served RPC HTTP response                     module=rest-server method=GET url="/staking/validators?status=unbonded" status=200 duration=1 remoteAddr=172.31.32.247:59094
I[2020-02-11|04:39:21.707] Served RPC HTTP response                     module=rest-server method=GET url=/gov/proposals status=200 duration=0 remoteAddr=172.31.32.247:59098
I[2020-02-11|04:39:26.709] Served RPC HTTP response                     module=rest-server method=GET url=/gov/proposals status=200 duration=0 remoteAddr=172.31.32.247:59110
```
All the IP addresses are correct: the node runs on one host, and the bigdipper runs on another host, both on a private network, while the bigdipper and the node are accessible from the Internet only on selected ports, but are both accessible to each other on all ports inside the private network.

**Comment by lacabra** [comment]
Debugging this issue, the culprit seems to be around [this line](https://github.com/forbole/big_dipper/blob/71b7a8fe617a7a92583e051451753f6c18c4c3be/imports/api/blocks/server/methods.js#L194).

And for comparison, this is the response I get from my RPC endpoint for this request: `RPC+'/block?height=' + height;` where `height=1`:

```
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "block_id": {
      "hash": "4959D23EED232A0F0430E933DF7C62007A2FBB47EFF57968AAE586AF46519FD8",
      "parts": {
        "total": "1",
        "hash": "BA2BFF44228C74D5987A5C5386C7AB73AF4B8BDF124EED4A856FB2E03EB8078A"
      }
    },
    "block": {
      "header": {
        "version": {
          "block": "10",
          "app": "0"
        },
        "chain_id": "enigma-testnet",
        "height": "1",
        "time": "2020-02-10T17:25:04.213874069Z",
        "last_block_id": {
          "hash": "",
          "parts": {
            "total": "0",
            "hash": ""
          }
        },
        "last_commit_hash": "",
        "data_hash": "",
        "validators_hash": "BE487BE3A83C8D5D2AF6CE918DEC6D8390C4B252A8CD6446E295647FF1A7F941",
        "next_validators_hash": "BE487BE3A83C8D5D2AF6CE918DEC6D8390C4B252A8CD6446E295647FF1A7F941",
        "consensus_hash": "048091BC7DDC283F77BFBF91D73C44DA58C3DF8A9CBC867405D8B7F3DAADA22F",
        "app_hash": "",
        "last_results_hash": "",
        "evidence_hash": "",
        "proposer_address": "F9B84D00B88B8D4FA15091B675C31CEB3420C9C2"
      },
      "data": {
        "txs": null
      },
      "evidence": {
        "evidence": null
      },
      "last_commit": {
        "height": "0",
        "round": "0",
        "block_id": {
          "hash": "",
          "parts": {
            "total": "0",
            "hash": ""
          }
        },
        "signatures": null
      }
    }
  }
}
```

There is no `block_meta`property. `block_id` is at the root of `result`.

Currently experimenting with adjusting the JSON response...

**Comment by lacabra** [comment]
@kwunyeung: I have figured it out. It seems that `cosmos/gaia` has changed the structure of the JSON response on the RPC endpoint for `RPC+'/block?height='` on their version `2.0`.

It seems we may need to branch out this repo into two, one to support their version `1.0` and another to support their version `2.0`; or somehow query the version through the RPC itself, and handle each version differently. Because this is a broader decision that goes well beyond fixing this issue, I am not going to submit a PR until a decision is made on how to handle the two versions. For now, and for the record, I got big_dipper working with version `2.0` of `cosmos/gaia` with the following changes:

```
diff --git a/imports/api/blocks/server/methods.js b/imports/api/blocks/server/methods.js
index 46b4164..cec7568 100644
--- a/imports/api/blocks/server/methods.js
+++ b/imports/api/blocks/server/methods.js
@@ -191,8 +191,8 @@ Meteor.methods({
                         // store height, hash, numtransaction and time in db
                         let blockData = {};
                         blockData.height = height;
-                        blockData.hash = block.block_meta.block_id.hash;
-                        blockData.transNum = block.block_meta.header.num_txs;
+                        blockData.hash = block.block_id.hash;
+                        blockData.transNum = block.block.data.txs ? block.block.data.txs.length : 0;
                         blockData.time = new Date(block.block.header.time);
                         blockData.lastBlockHash = block.block.header.last_block_id.hash;
                         blockData.proposerAddress = block.block.header.proposer_address;
@@ -314,7 +314,7 @@ Meteor.methods({
                             }
                         }
 
-                        let chainStatus = Chain.findOne({chainId:block.block_meta.header.chain_id});
+                        let chainStatus = Chain.findOne({chainId:block.block.header.chain_id});
                         let lastSyncedTime = chainStatus?chainStatus.lastSyncedTime:0;
                         let timeDiff;
                         let blockTime = Meteor.settings.params.defaultBlockTime;
@@ -328,7 +328,7 @@ Meteor.methods({
                         let endGetValidatorsTime = new Date();
                         console.log("Get height validators time: "+((endGetValidatorsTime-startGetValidatorsTime)/1000)+"seconds.");
 
-                        Chain.update({chainId:block.block_meta.header.chain_id}, {$set:{lastSyncedTime:blockData.time, blockTime:blockTime}});
+                        Chain.update({chainId:block.block.header.chain_id}, {$set:{lastSyncedTime:blockData.time, blockTime:blockTime}});
 
                         analyticsData.averageBlockTime = blockTime;
                         analyticsData.timeDiff = timeDiff;
```

**Comment by kwunyeung** [comment]
@lacabra Thanks! I think this is the latest changes on Tendermint. The RPC node running for https://cosmos.bigdipper.live is `v2.0.4`. They should have bumped the Tendermint version in `v2.0.6`.

**Comment by kwunyeung** [comment]
@lacabra @lacabra I have tested the latest code with `v2.0.6`. I don't have the issue you mentioned. You may take a look at this block. It's the `gaia-13007` testnet running with `gaia v2.0.6`.

http://rpc.gaia.bigdipper.live:26657/block?height=1

On the other hand, there is a bug in the SDK `v0.37.9` and `v0.38` that blocks Big Dipper reading the transactions.

https://github.com/cosmos/cosmos-sdk/issues/5592

For your `enigma-testnet`, are you developing with SDK `v0.38?` The `v0.38` is running with `Tendermint v0.33` which the `BlockMeta` has been removed.

https://github.com/tendermint/tendermint/blob/master/CHANGELOG.md#breaking-changes

**Comment by kwunyeung** [comment]
@lacabra do you still have problem with this?
