### ISSUE TITLE
Validators are not displayed for Cosmos SDK ibc-alpha branch

### ISSUE THREAD

**Issue by michaelfig** [forbole/big-dipper#311]
**Describe the bug**

I get the following error when starting meteor on a fresh MongoDB database: `ReferenceError: profileUrl is not defined`

**To Reproduce**

1. Check out the `kwun/sdk-v0.38.x` branch
2. Create the `settings.json`
  <details><summary>`settings.json` contents</summary>
```json
{
    "public":{
        "chainName": "Agoric Testnet",
        "chainId": "testnet-1.17.0",
        "gtm": "{Add your Google Tag Manager ID here}",
        "slashingWindow": 10000,
        "uptimeWindow": 250,
        "initialPageSize": 30,
        "bech32PrefixAccAddr": "cosmos",
        "bech32PrefixAccPub": "cosmospub",
        "bech32PrefixValAddr": "cosmosvaloper",
        "bech32PrefixValPub": "cosmosvaloperpub",
        "bech32PrefixConsAddr": "cosmosvalcons",
        "bech32PrefixConsPub": "cosmosvalconspub",
        "bondDenom": "uagstake",
        "powerReduction": 1000000,
        "coins": [
            {
                "denom": "uagstake",
                "displayName": "AGSTAKE",
                "displayNamePlural": "AGSTAKES",
                "fraction": 1000000
            }
        ],
        "gasPrice": 0.00,
        "coingeckoId": null
    },
    "genesisFile": "https://testnet.agoric.com/genesis.json",
    "remote":{
        "rpc":"http://178.62.245.23:26657",
        "lcd":"http://127.0.0.1:1317"
    },
    "debug": {
        "startTimer": true,
        "readGenesis": true
    },
    "params":{
        "startHeight": 0,
        "defaultBlockTime": 5000,
        "blockInterval": 15000,
        "consensusInterval": 1000,
        "statusInterval":7500,
        "signingInfoInterval": 1800000,
        "proposalInterval": -1,
        "missedBlocksInterval": 60000,
        "delegationInterval": 900000
    }
}
```

</details>
3. Destroy the MongoDB database: `meteor reset`
4. Run `meteor npm install --save`
5. Run `meteor --settings settings.json`

**Expected behavior**
No errors.

**Screenshots**

<details><summary>log messages from starting meteor with the above settings.json</summary>

```
I20200309-15:57:47.417(0)? Block insert time: 0.01seconds.
I20200309-15:57:47.423(0)? Get height validators time: 0.181seconds.
I20200309-15:57:47.425(0)? validatorSet size: 1
I20200309-15:57:47.462(0)? Fetching keybase...
I20200309-15:57:47.464(0)? http://178.62.245.23:26657/validators?height=1&page=1&per_page=100
I20200309-15:57:47.673(0)? ReferenceError: profileUrl is not defined
I20200309-15:57:47.674(0)?     at imports/api/blocks/server/methods.js:561:49
I20200309-15:57:47.674(0)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1102:16)
I20200309-15:57:47.674(0)?     at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:882:44)
I20200309-15:57:47.674(0)?     at MethodInvocation.blocks.blocksUpdate (imports/api/blocks/server/methods.js:553:49)
I20200309-15:57:47.675(0)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20200309-15:57:47.675(0)?     at packages/ddp-server/livedata_server.js:1689:15
I20200309-15:57:47.675(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20200309-15:57:47.675(0)?     at packages/ddp-server/livedata_server.js:1687:36
I20200309-15:57:47.675(0)?     at new Promise (<anonymous>)
I20200309-15:57:47.676(0)?     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
I20200309-15:57:47.676(0)?     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
I20200309-15:57:47.676(0)?     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
I20200309-15:57:47.676(0)?     at updateBlock (server/main.js:36:12)
I20200309-15:57:47.677(0)?     at server/main.js:193:21
I20200309-15:57:47.677(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20200309-15:57:47.677(0)?     at packages/meteor.js:550:25
I20200309-15:57:47.677(0)?     at runWithEnvironment (packages/meteor.js:1286:24)
I20200309-15:57:47.677(0)? updateBlocks: Stopped
```

</details>

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

Running on `linux_x64` (recent Ubuntu).  Agoric testnet-1.17.0.

**Comment by kwunyeung** [comment]
Looks like I didn't push the commits after I have updated the avatar. Can you try pulling the branch again and see if it works? Otherwise, I will upgrade our test node tomorrow and see what is incompatible.

**Comment by michaelfig** [comment]
I pulled again.  After starting from scratch, the `node0` validator appeared in the active validators list, but as soon as it reached a block where other validators were added with `create-validator`, the active validators (and random validators) were cleared.

![Screen Shot 2020-03-10 at 9 32 42 AM](https://user-images.githubusercontent.com/457244/76329853-b6469080-62b2-11ea-8a31-c0fad36a4fb9.png)
![Screen Shot 2020-03-10 at 9 31 25 AM](https://user-images.githubusercontent.com/457244/76329861-b9da1780-62b2-11ea-96d4-f1800a9cd8a7.png)

**Comment by michaelfig** [comment]
Here are the contents of the `validators` collection:

```json
[
  {
    "_id": "HTzJxwWsL3W37fidT",
    "consensus_pubkey": "cosmosvalconspub1zcjduepqqevhm6sh0n9x3jcyz7xevhlsn36ef62z9cye4pxzayrl42ycrq4s7dgt3s",
    "description": {
      "moniker": "node0"
    },
    "commission": {
      "commission_rates": {
        "rate": "0.100000000000000000",
        "max_rate": "0.200000000000000000",
        "max_change_rate": "0.010000000000000000"
      },
      "update_time": "2020-03-02T18:41:36.681842479Z"
    },
    "min_self_delegation": "1",
    "operator_address": "cosmosvaloper1jkmhgct3ztatf90v566dgd0pmucnhr8atfjdq0",
    "delegator_address": "cosmos1jkmhgct3ztatf90v566dgd0pmucnhr8awaxcvu",
    "voting_power": 2,
    "jailed": false,
    "status": 3,
    "pub_key": {
      "type": "tendermint/PubKeyEd25519",
      "value": "Bll96hd8ymjLBBeNll/wnHWU6UIuCZqEwukH+qiYGCs="
    },
    "address": "B6E6C700D11BBE7C985947C8032D5BC727B159B4",
    "accpub": "cosmospub1zcjduepqqevhm6sh0n9x3jcyz7xevhlsn36ef62z9cye4pxzayrl42ycrq4srmdqtz",
    "operator_pubkey": "cosmosvaloperpub1zcjduepqqevhm6sh0n9x3jcyz7xevhlsn36ef62z9cye4pxzayrl42ycrq4sn80d7c",
    "delegator_shares": "2000000.000000000000000000",
    "proposer_priority": 4,
    "tokens": "2000000",
    "unbonding_time": "1970-01-01T00:00:00Z",
    "lastSeen": {
      "$date": "2020-03-02T22:37:14.33Z"
    },
    "uptime": 100,
    "self_delegation": 1
  },
  {
    "_id": {
      "$oid": "5e67b1f6e7382f0d52c2b3fd"
    },
    "address": "63215FDEC04D3E9967757C09F55CD3356E8B4640",
    "accpub": "cosmospub1zcjduepqa7wqpha8lx5dyfju7dfhd06u2qhrzwcuj5p4tk8svw9z0wlyqrhqa6kr83",
    "commission": {
      "commission_rates": {
        "rate": "0.100000000000000000",
        "max_rate": "0.200000000000000000",
        "max_change_rate": "0.010000000000000000"
      },
      "update_time": "2020-03-02T19:03:13.14905799Z"
    },
    "consensus_pubkey": "cosmosvalconspub1zcjduepqa7wqpha8lx5dyfju7dfhd06u2qhrzwcuj5p4tk8svw9z0wlyqrhqqvngar",
    "delegator_address": "cosmos17pj4xhd7r4kjg9zhuf5k6agnw35a5dqjxa6eva",
    "delegator_shares": "2000000.000000000000000000",
    "description": {
      "moniker": "node1"
    },
    "min_self_delegation": "1",
    "operator_address": "cosmosvaloper17pj4xhd7r4kjg9zhuf5k6agnw35a5dqjrfwvqw",
    "operator_pubkey": "cosmosvaloperpub1zcjduepqa7wqpha8lx5dyfju7dfhd06u2qhrzwcuj5p4tk8svw9z0wlyqrhqdx5wjt",
    "proposer_priority": -8,
    "pub_key": {
      "type": "tendermint/PubKeyEd25519",
      "value": "75wA36f5qNImXPNTdr9cUC4xOxyVA1XY8GOKJ7vkAO4="
    },
    "self_delegation": 1,
    "status": 3,
    "tokens": "1980000",
    "unbonding_height": "44583",
    "unbonding_time": "2020-03-26T16:37:31.208116788Z",
    "voting_power": 2,
    "lastSeen": {
      "$date": "2020-03-02T22:37:14.33Z"
    },
    "uptime": 100
  },
  {
    "_id": {
      "$oid": "5e67b202e7382f0d52c2b472"
    },
    "address": "CDFD41D6AFA86E9AF351BAD89A90FA5C7804B713",
    "accpub": "cosmospub1zcjduepqlwx4dgk0cvtgk0zz70jg44vwj3j5mqrukk454nh6rpl6yp8nyzfsvsu5kr",
    "commission": {
      "commission_rates": {
        "rate": "0.100000000000000000",
        "max_rate": "0.200000000000000000",
        "max_change_rate": "0.010000000000000000"
      },
      "update_time": "2020-03-02T19:03:28.465225638Z"
    },
    "consensus_pubkey": "cosmosvalconspub1zcjduepqlwx4dgk0cvtgk0zz70jg44vwj3j5mqrukk454nh6rpl6yp8nyzfs3xelv3",
    "delegator_address": "cosmos18y22f3nqy30ydsxmzqj03960uekeql88mnh6xd",
    "delegator_shares": "2000000.000000000000000000",
    "description": {
      "moniker": "node3"
    },
    "min_self_delegation": "1",
    "operator_address": "cosmosvaloper18y22f3nqy30ydsxmzqj03960uekeql8878r027",
    "operator_pubkey": "cosmosvaloperpub1zcjduepqlwx4dgk0cvtgk0zz70jg44vwj3j5mqrukk454nh6rpl6yp8nyzfsuv7ere",
    "proposer_priority": 0,
    "pub_key": {
      "type": "tendermint/PubKeyEd25519",
      "value": "+41Wos/DFos8QvPkitWOlGVNgHy1q0rO+hh/ogTzIJM="
    },
    "self_delegation": 1,
    "status": 3,
    "tokens": "1980000",
    "unbonding_height": "46975",
    "unbonding_time": "2020-03-26T20:20:14.125444887Z",
    "voting_power": 2,
    "lastSeen": {
      "$date": "2020-03-02T22:37:14.33Z"
    },
    "uptime": 100
  },
  {
    "_id": {
      "$oid": "5e67b203e7382f0d52c2b487"
    },
    "address": "C1B2888C3F8839ED268972F3AE69DAC3E152F9F9",
    "accpub": "cosmospub1zcjduepqyqwdhxzddvns0dz68wr68scv2zgsawzvcclqgcaqh0jrv2mulrws36d80d",
    "commission": {
      "commission_rates": {
        "rate": "0.100000000000000000",
        "max_rate": "0.200000000000000000",
        "max_change_rate": "0.010000000000000000"
      },
      "update_time": "2020-03-02T19:03:39.667275746Z"
    },
    "consensus_pubkey": "cosmosvalconspub1zcjduepqyqwdhxzddvns0dz68wr68scv2zgsawzvcclqgcaqh0jrv2mulrwsvvgv4l",
    "delegator_address": "cosmos10lvqta75ahkcs643e8h4kzjg7uvtmyuw3ed83w",
    "delegator_shares": "2000000.000000000000000000",
    "description": {
      "moniker": "node2"
    },
    "min_self_delegation": "1",
    "operator_address": "cosmosvaloper10lvqta75ahkcs643e8h4kzjg7uvtmyuw5dejaa",
    "operator_pubkey": "cosmosvaloperpub1zcjduepqyqwdhxzddvns0dz68wr68scv2zgsawzvcclqgcaqh0jrv2mulrwspx026h",
    "proposer_priority": 3,
    "pub_key": {
      "type": "tendermint/PubKeyEd25519",
      "value": "IBzbmE1rJwe0WjuHo8MMUJEOuEzGPgRjoLvkNit8+N0="
    },
    "self_delegation": 1,
    "status": 3,
    "tokens": "1980000",
    "unbonding_height": "47891",
    "unbonding_time": "2020-03-26T21:46:44.71786639Z",
    "voting_power": 2,
    "lastSeen": {
      "$date": "2020-03-02T22:37:14.33Z"
    },
    "uptime": 100
  },
  {
    "_id": {
      "$oid": "5e67b204e7382f0d52c2b4be"
    },
    "address": "6ECD788D49000CDD22E21755B7AEEE2736E2E916",
    "accpub": "cosmospub1zcjduepqz2mj4t4t922rynzn35ej0ef3l2au2yefm353c9lcaz87ftn5jhjsa43a2y",
    "commission": {
      "commission_rates": {
        "rate": "0.100000000000000000",
        "max_rate": "0.200000000000000000",
        "max_change_rate": "0.010000000000000000"
      },
      "update_time": "2020-03-02T19:03:50.906302218Z"
    },
    "consensus_pubkey": "cosmosvalconspub1zcjduepqz2mj4t4t922rynzn35ej0ef3l2au2yefm353c9lcaz87ftn5jhjsqr5ksk",
    "delegator_address": "cosmos1svvvavk6zstl9natslnvxszzyetju36tsrqswh",
    "delegator_shares": "2000000.000000000000000000",
    "description": {
      "moniker": "node5"
    },
    "min_self_delegation": "1",
    "operator_address": "cosmosvaloper1svvvavk6zstl9natslnvxszzyetju36t4h59zy",
    "operator_pubkey": "cosmosvaloperpub1zcjduepqz2mj4t4t922rynzn35ej0ef3l2au2yefm353c9lcaz87ftn5jhjsdfnsl7",
    "proposer_priority": 1,
    "pub_key": {
      "type": "tendermint/PubKeyEd25519",
      "value": "ErcqrqsqlDJMU40zJ+Ux+rvFEyncaRwX+OiP5K50leU="
    },
    "self_delegation": 1,
    "status": 3,
    "tokens": "1970000",
    "unbonding_height": "1494",
    "unbonding_time": "2020-03-23T21:22:51.54595415Z",
    "voting_power": 1,
    "lastSeen": {
      "$date": "2020-03-02T22:37:14.33Z"
    },
    "uptime": 58.4
  },
  {
    "_id": {
      "$oid": "5e67b205e7382f0d52c2b4f6"
    },
    "address": "445EFB387AD6A05CAA5C38B5A15F6CEC2D61078A",
    "accpub": "cosmospub1zcjduepqy4vedu7qmsgt77lqzgel7ruvzlmmxk388s63le794gz2ca6qdepsw8p039",
    "commission": {
      "commission_rates": {
        "rate": "0.100000000000000000",
        "max_rate": "0.200000000000000000",
        "max_change_rate": "0.010000000000000000"
      },
      "update_time": "2020-03-02T19:04:01.827146299Z"
    },
    "consensus_pubkey": "cosmosvalconspub1zcjduepqy4vedu7qmsgt77lqzgel7ruvzlmmxk388s63le794gz2ca6qdepsn3yyth",
    "delegator_address": "cosmos1t6xlln02ac7ruh8cphu4q0m9kcklapua2mcq4v",
    "delegator_shares": "2000000.000000000000000000",
    "description": {
      "moniker": "node4"
    },
    "min_self_delegation": "1",
    "operator_address": "cosmosvaloper1t6xlln02ac7ruh8cphu4q0m9kcklapua00v4el",
    "operator_pubkey": "cosmosvaloperpub1zcjduepqy4vedu7qmsgt77lqzgel7ruvzlmmxk388s63le794gz2ca6qdeps7mrzyl",
    "proposer_priority": -2,
    "pub_key": {
      "type": "tendermint/PubKeyEd25519",
      "value": "JVmW88DcEL974BIz/w+MF/ezWic8NR/nxaoErHdAbkM="
    },
    "self_delegation": 1,
    "status": 3,
    "tokens": "2000000",
    "unbonding_time": "1970-01-01T00:00:00Z",
    "voting_power": 2,
    "lastSeen": {
      "$date": "2020-03-02T22:37:14.33Z"
    },
    "uptime": 100
  },
  {
    "_id": {
      "$oid": "5e67b205e7382f0d52c2b52f"
    },
    "address": "CDF1368C6D285E612091F36ADB91A60478FA0480",
    "accpub": "cosmospub1zcjduepqellnaar2cs2edaqp45qjc2rma5rs292jqr0sqsgjwd68j9ckat6sdk9ut6",
    "commission": {
      "commission_rates": {
        "rate": "0.100000000000000000",
        "max_rate": "0.200000000000000000",
        "max_change_rate": "0.010000000000000000"
      },
      "update_time": "2020-03-02T19:04:12.890837781Z"
    },
    "consensus_pubkey": "cosmosvalconspub1zcjduepqellnaar2cs2edaqp45qjc2rma5rs292jqr0sqsgjwd68j9ckat6ssqqh3g",
    "delegator_address": "cosmos1vhd2tvwxvuxx3j6d8j3w2vdk20mx2cvlvfqf72",
    "delegator_shares": "2000000.000000000000000000",
    "description": {
      "moniker": "node6"
    },
    "min_self_delegation": "1",
    "operator_address": "cosmosvaloper1vhd2tvwxvuxx3j6d8j3w2vdk20mx2cvlfa5uje",
    "operator_pubkey": "cosmosvaloperpub1zcjduepqellnaar2cs2edaqp45qjc2rma5rs292jqr0sqsgjwd68j9ckat6sa2837q",
    "proposer_priority": 4,
    "pub_key": {
      "type": "tendermint/PubKeyEd25519",
      "value": "z/8+9GrEFZb0Aa0BLCh77QcFFVIA3wBBEnN0eRcW6vU="
    },
    "self_delegation": 1,
    "status": 3,
    "tokens": "1980000",
    "unbonding_height": "31587",
    "unbonding_time": "2020-03-25T20:19:47.854974395Z",
    "voting_power": 2,
    "lastSeen": {
      "$date": "2020-03-02T22:37:14.33Z"
    },
    "uptime": 100
  },
  {
    "_id": {
      "$oid": "5e67b3c9e7382f0d52c341a4"
    },
    "address": "A2A302172492FB85AE13EA6A6FF5E966FAA0798E",
    "accpub": "cosmospub1zcjduepqw8h4l0serpwt5evc2zwtg4phnepd8yzz87e8mewg4yhsl40rvtmqt4fxl6",
    "commission": {
      "commission_rates": {
        "rate": "0.100000000000000000",
        "max_rate": "0.200000000000000000",
        "max_change_rate": "0.010000000000000000"
      },
      "update_time": "2020-03-02T20:57:12.674894658Z"
    },
    "consensus_pubkey": "cosmosvalconspub1zcjduepqw8h4l0serpwt5evc2zwtg4phnepd8yzz87e8mewg4yhsl40rvtmqkrvd9g",
    "delegator_address": "cosmos1pu5mgemh58aymecc9nvdemtnv0cyw8l88mt3je",
    "delegator_shares": "2000000.000000000000000000",
    "description": {
      "moniker": "DokiaCapital"
    },
    "min_self_delegation": "1",
    "operator_address": "cosmosvaloper1pu5mgemh58aymecc9nvdemtnv0cyw8l8z0ly72",
    "operator_pubkey": "cosmosvaloperpub1zcjduepqw8h4l0serpwt5evc2zwtg4phnepd8yzz87e8mewg4yhsl40rvtmqmftt2q",
    "proposer_priority": -1,
    "pub_key": {
      "type": "tendermint/PubKeyEd25519",
      "value": "ce9fvhkYXLplmFCctFQ3nkLTkEI/sn3lyKkvD9XjYvY="
    },
    "self_delegation": 1,
    "status": 3,
    "tokens": "2000000",
    "unbonding_time": "1970-01-01T00:00:00Z",
    "voting_power": 2,
    "lastSeen": {
      "$date": "2020-03-02T22:37:14.33Z"
    },
    "uptime": 100
  }
]
```

**Comment by kwunyeung** [comment]
@michaelfig there are a lot of changes in the `ibc-alpha` branch. I have made a little changes for you so that you can show the active validators correctly. I have also commented the `minting` requests for now. Please pull from https://github.com/forbole/big-dipper/tree/kwun/ibc-alpha branch and try again.

FYR, the value of `BondStatus` for a validator has been shifted from `0, 1 and 2` to `1, 2 and 3`. Originally `2` was `bonded validator` but now it's `3`. That's the reason for not showing the validators in the active list.
