### ISSUE TITLE
Crash: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#361]
**Describe the bug**
I believe I have seen this happen several times before. I am running in non-production mode, and Big Dipper crashes. Please see screenshots below in the "screenshots" section. I have also included in this section the output from the meteor server process.

```
I20200531-15:45:17.973(0)? http://d.sentry.testnet.public.bluzelle.com:1317/minting/annual-provisions
I20200531-15:45:17.973(0)? Error: failed [404] 404 page not found
I20200531-15:45:17.973(0)?     at Object.exports.makeErrorByStatus (packages/http.js:177:10)
I20200531-15:45:17.974(0)?     at Request._callback (packages/http.js:141:24)
I20200531-15:45:17.974(0)?     at Request.self.callback (/home/ubuntu/.meteor/packages/http/.1.4.2.1fotq9x.lz1d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:185:22)
I20200531-15:45:17.974(0)?     at Request.emit (events.js:311:20)
I20200531-15:45:17.974(0)?     at Request.EventEmitter.emit (domain.js:482:12)
I20200531-15:45:17.974(0)?     at Request.<anonymous> (/home/ubuntu/.meteor/packages/http/.1.4.2.1fotq9x.lz1d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:1161:10)
I20200531-15:45:17.974(0)?     at Request.emit (events.js:311:20)
I20200531-15:45:17.974(0)?     at Request.EventEmitter.emit (domain.js:482:12)
I20200531-15:45:17.974(0)?     at IncomingMessage.<anonymous> (/home/ubuntu/.meteor/packages/http/.1.4.2.1fotq9x.lz1d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:1083:12)
I20200531-15:45:17.975(0)?     at Object.onceWrapper (events.js:417:28)
I20200531-15:45:17.975(0)?     at IncomingMessage.emit (events.js:323:22)
I20200531-15:45:17.975(0)?     at IncomingMessage.EventEmitter.emit (domain.js:482:12)
I20200531-15:45:17.975(0)?     at endReadableNT (_stream_readable.js:1204:12)
I20200531-15:45:17.975(0)?     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
I20200531-15:45:17.975(0)?   response: {
I20200531-15:45:17.975(0)?     statusCode: 404,
I20200531-15:45:17.975(0)?     content: '404 page not found\n',
I20200531-15:45:17.976(0)?     headers: {
I20200531-15:45:17.976(0)?       server: 'nginx/1.17.10',
I20200531-15:45:17.976(0)?       date: 'Sun, 31 May 2020 15:45:17 GMT',
I20200531-15:45:17.976(0)?       'content-type': 'text/plain; charset=utf-8',
I20200531-15:45:17.976(0)?       'content-length': '19',
I20200531-15:45:17.976(0)?       connection: 'close',
I20200531-15:45:17.976(0)?       'x-content-type-options': 'nosniff',
I20200531-15:45:17.976(0)?       'x-server-time': '1590939917',
I20200531-15:45:17.976(0)?       'access-control-allow-origin': '*',
I20200531-15:45:17.977(0)?       'access-control-allow-credentials': 'true',
I20200531-15:45:17.977(0)?       'access-control-allow-headers': 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range',
I20200531-15:45:17.977(0)?       'access-control-allow-methods': 'GET,POST,OPTIONS,PUT,DELETE,PATCH'
I20200531-15:45:17.977(0)?     },
I20200531-15:45:17.977(0)?     data: null
I20200531-15:45:17.977(0)?   }
I20200531-15:45:17.977(0)? }
I20200531-15:45:18.113(0)? updateStatus: 30090
I20200531-15:45:18.663(0)? Get tx: 48E07D6AA6C2453D99794BA7F65D3F8419A6B4202D045C8593213769C8B9CB1A
I20200531-15:45:25.298(0)? 48E07D6AA6C2453D99794BA7F65D3F8419A6B4202D045C8593213769C8B9CB1A
I20200531-15:45:25.300(0)? get proposals result: true
I20200531-15:45:25.326(0)? http://d.sentry.testnet.public.bluzelle.com:1317/staking/validators?status=unbonded
I20200531-15:45:25.326(0)? BulkWriteError: E11000 duplicate key error collection: meteor.transactions index: txhash_1 dup key: { txhash: "48E07D6AA6C2453D99794BA7F65D3F8419A6B4202D045C8593213769C8B9CB1A" }
I20200531-15:45:25.326(0)?     at OrderedBulkOperation.handleWriteError (/home/ubuntu/.meteor/packages/npm-mongo/.3.7.1.qp9w6.gtchni++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/common.js:1210:11)
I20200531-15:45:25.327(0)?     at resultHandler (/home/ubuntu/.meteor/packages/npm-mongo/.3.7.1.qp9w6.gtchni++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/common.js:519:23)
I20200531-15:45:25.327(0)?     at /home/ubuntu/.meteor/packages/npm-mongo/.3.7.1.qp9w6.gtchni++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/connection/pool.js:404:18
I20200531-15:45:25.327(0)?     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
I20200531-15:45:25.327(0)?   index: 0,
I20200531-15:45:25.327(0)?   code: 11000,
I20200531-15:45:25.327(0)?   errmsg: 'E11000 duplicate key error collection: meteor.transactions index: txhash_1 dup key: { txhash: "48E07D6AA6C2453D99794BA7F65D3F8419A6B4202D045C8593213769C8B9CB1A" }',
I20200531-15:45:25.327(0)?   op: {
I20200531-15:45:25.327(0)?     height: 30091,
I20200531-15:45:25.327(0)?     txhash: '48E07D6AA6C2453D99794BA7F65D3F8419A6B4202D045C8593213769C8B9CB1A',
I20200531-15:45:25.328(0)?     codespace: 'sdk',
I20200531-15:45:25.328(0)?     code: 11,
I20200531-15:45:25.328(0)?     raw_log: 'out of gas: out of gas in location: WriteFlat; gasWanted: 46993, gasUsed: 47940',
I20200531-15:45:25.328(0)?     gas_wanted: '46993',
I20200531-15:45:25.328(0)?     gas_used: '47940',
I20200531-15:45:25.328(0)?     tx: { type: 'cosmos-sdk/StdTx', value: [Object] },
I20200531-15:45:25.328(0)?     timestamp: '2020-05-31T15:45:10Z',
I20200531-15:45:25.328(0)?     _id: 'RzsEwyzsBch6GmuN8'
I20200531-15:45:25.328(0)?   },
I20200531-15:45:25.329(0)?   name: 'BulkWriteError',
I20200531-15:45:25.329(0)?   driver: true,
I20200531-15:45:25.329(0)?   err: {
I20200531-15:45:25.329(0)?     index: 0,
I20200531-15:45:25.329(0)?     code: 11000,
I20200531-15:45:25.329(0)?     errmsg: 'E11000 duplicate key error collection: meteor.transactions index: txhash_1 dup key: { txhash: "48E07D6AA6C2453D99794BA7F65D3F8419A6B4202D045C8593213769C8B9CB1A" }',
I20200531-15:45:25.329(0)?     op: {
I20200531-15:45:25.329(0)?       height: 30091,
I20200531-15:45:25.329(0)?       txhash: '48E07D6AA6C2453D99794BA7F65D3F8419A6B4202D045C8593213769C8B9CB1A',
I20200531-15:45:25.329(0)?       codespace: 'sdk',
I20200531-15:45:25.330(0)?       code: 11,
I20200531-15:45:25.330(0)?       raw_log: 'out of gas: out of gas in location: WriteFlat; gasWanted: 46993, gasUsed: 47940',
I20200531-15:45:25.330(0)?       gas_wanted: '46993',
I20200531-15:45:25.330(0)?       gas_used: '47940',
I20200531-15:45:25.330(0)?       tx: [Object],
I20200531-15:45:25.330(0)?       timestamp: '2020-05-31T15:45:10Z',
I20200531-15:45:25.330(0)?       _id: 'RzsEwyzsBch6GmuN8'   
I20200531-15:45:25.330(0)?     }
I20200531-15:45:25.330(0)?   },
I20200531-15:45:25.331(0)?   result: BulkWriteResult {
I20200531-15:45:25.331(0)?     result: {
I20200531-15:45:25.331(0)?       ok: 1,
I20200531-15:45:25.331(0)?       writeErrors: [Array],
I20200531-15:45:25.331(0)?       writeConcernErrors: [],
I20200531-15:45:25.331(0)?       insertedIds: [Array],
I20200531-15:45:25.331(0)?       nInserted: 0,
I20200531-15:45:25.331(0)?       nUpserted: 0,
I20200531-15:45:25.331(0)?       nMatched: 0,
I20200531-15:45:25.331(0)?       nModified: 0,
I20200531-15:45:25.332(0)?       nRemoved: 0,
I20200531-15:45:25.332(0)?       upserted: [],
I20200531-15:45:25.332(0)?       lastOp: [Object]
I20200531-15:45:25.332(0)?     }
I20200531-15:45:25.332(0)?   },
I20200531-15:45:25.332(0)?   [Symbol(mongoErrorContextSymbol)]: {}
I20200531-15:45:25.332(0)? }
I20200531-15:45:25.332(0)? Get tx: EF5D1A3FD3D214D1FD269C59DF29F3E31F6D8A700B15295D282025524479E6BD
I20200531-15:45:25.691(0)? get proposal: true
I20200531-15:45:25.703(0)? EF5D1A3FD3D214D1FD269C59DF29F3E31F6D8A700B15295D282025524479E6BD
I20200531-15:45:25.707(0)? http://d.sentry.testnet.public.bluzelle.com:1317/staking/validators?status=unbonded
I20200531-15:45:25.707(0)? BulkWriteError: E11000 duplicate key error collection: meteor.transactions index: txhash_1 dup key: { txhash: "EF5D1A3FD3D214D1FD269C59DF29F3E31F6D8A700B15295D282025524479E6BD" }
I20200531-15:45:25.707(0)?     at OrderedBulkOperation.handleWriteError (/home/ubuntu/.meteor/packages/npm-mongo/.3.7.1.qp9w6.gtchni++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/common.js:1210:11)
I20200531-15:45:25.707(0)?     at resultHandler (/home/ubuntu/.meteor/packages/npm-mongo/.3.7.1.qp9w6.gtchni++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/common.js:519:23)
I20200531-15:45:25.708(0)?     at /home/ubuntu/.meteor/packages/npm-mongo/.3.7.1.qp9w6.gtchni++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/connection/pool.js:404:18
I20200531-15:45:25.708(0)?     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
I20200531-15:45:25.708(0)?   index: 0,
I20200531-15:45:25.708(0)?   code: 11000,
I20200531-15:45:25.708(0)?   errmsg: 'E11000 duplicate key error collection: meteor.transactions index: txhash_1 dup key: { txhash: "EF5D1A3FD3D214D1FD269C59DF29F3E31F6D8A700B15295D282025524479E6BD" }',
I20200531-15:45:25.708(0)?   op: {
I20200531-15:45:25.708(0)?     height: 30092,
I20200531-15:45:25.708(0)?     txhash: 'EF5D1A3FD3D214D1FD269C59DF29F3E31F6D8A700B15295D282025524479E6BD',
I20200531-15:45:25.708(0)?     codespace: 'sdk',
I20200531-15:45:25.708(0)?     code: 11,
I20200531-15:45:25.709(0)?     raw_log: 'out of gas: out of gas in location: WriteFlat; gasWanted: 47146, gasUsed: 48082',
I20200531-15:45:25.709(0)?     gas_wanted: '47146',
I20200531-15:45:25.709(0)?     gas_used: '48082',
I20200531-15:45:25.709(0)?     tx: { type: 'cosmos-sdk/StdTx', value: [Object] },
I20200531-15:45:25.709(0)?     timestamp: '2020-05-31T15:45:16Z',
I20200531-15:45:25.709(0)?     _id: 'QqigypAPFqycfNxTb'
I20200531-15:45:25.709(0)?   },
I20200531-15:45:25.709(0)?   name: 'BulkWriteError',
I20200531-15:45:25.709(0)?   driver: true,
I20200531-15:45:25.710(0)?   err: {
I20200531-15:45:25.710(0)?     index: 0,
I20200531-15:45:25.710(0)?     code: 11000,
I20200531-15:45:25.710(0)?     errmsg: 'E11000 duplicate key error collection: meteor.transactions index: txhash_1 dup key: { txhash: "EF5D1A3FD3D214D1FD269C59DF29F3E31F6D8A700B15295D282025524479E6BD" }',
I20200531-15:45:25.710(0)?     op: {
I20200531-15:45:25.710(0)?       height: 30092,
I20200531-15:45:25.710(0)?       txhash: 'EF5D1A3FD3D214D1FD269C59DF29F3E31F6D8A700B15295D282025524479E6BD',
I20200531-15:45:25.710(0)?       codespace: 'sdk',
I20200531-15:45:25.710(0)?       code: 11,
I20200531-15:45:25.710(0)?       raw_log: 'out of gas: out of gas in location: WriteFlat; gasWanted: 47146, gasUsed: 48082',
I20200531-15:45:25.711(0)?       gas_wanted: '47146',
I20200531-15:45:25.711(0)?       gas_used: '48082',
I20200531-15:45:25.711(0)?       tx: [Object],
I20200531-15:45:25.711(0)?       timestamp: '2020-05-31T15:45:16Z',
I20200531-15:45:25.711(0)?       _id: 'QqigypAPFqycfNxTb'   
I20200531-15:45:25.711(0)?     }
I20200531-15:45:25.711(0)?   },
I20200531-15:45:25.711(0)?   result: BulkWriteResult {
I20200531-15:45:25.711(0)?     result: {
I20200531-15:45:25.714(0)?       ok: 1,
I20200531-15:45:25.714(0)?       writeErrors: [Array],
I20200531-15:45:25.714(0)?       writeConcernErrors: [],
I20200531-15:45:25.714(0)?       insertedIds: [Array],
I20200531-15:45:25.714(0)?       nInserted: 0,
I20200531-15:45:25.714(0)?       nUpserted: 0,
I20200531-15:45:25.714(0)?       nMatched: 0,
I20200531-15:45:25.714(0)?       nModified: 0,
I20200531-15:45:25.714(0)?       nRemoved: 0,
I20200531-15:45:25.715(0)?       upserted: [],
I20200531-15:45:25.715(0)?       lastOp: [Object]
I20200531-15:45:25.715(0)?     }
I20200531-15:45:25.715(0)?   },
I20200531-15:45:25.715(0)?   [Symbol(mongoErrorContextSymbol)]: {}
I20200531-15:45:25.715(0)? }
I20200531-15:45:25.715(0)? Get tx: D1DD554F37623AB0A597F1CF1E365A63F048F501D656DDA69A228F0F066C1A51
I20200531-15:45:26.134(0)? D1DD554F37623AB0A597F1CF1E365A63F048F501D656DDA69A228F0F066C1A51
I20200531-15:45:26.149(0)? http://d.sentry.testnet.public.bluzelle.com:1317/staking/validators?status=unbonded
I20200531-15:45:26.150(0)? BulkWriteError: E11000 duplicate key error collection: meteor.transactions index: txhash_1 dup key: { txhash: "D1DD554F37623AB0A597F1CF1E365A63F048F501D656DDA69A228F0F066C1A51" }
I20200531-15:45:26.150(0)?     at OrderedBulkOperation.handleWriteError (/home/ubuntu/.meteor/packages/npm-mongo/.3.7.1.qp9w6.gtchni++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/common.js:1210:11)
I20200531-15:45:26.150(0)?     at resultHandler (/home/ubuntu/.meteor/packages/npm-mongo/.3.7.1.qp9w6.gtchni++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/common.js:519:23)
I20200531-15:45:26.150(0)?     at /home/ubuntu/.meteor/packages/npm-mongo/.3.7.1.qp9w6.gtchni++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/connection/pool.js:404:18
I20200531-15:45:26.150(0)?     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
I20200531-15:45:26.151(0)?   index: 0,
I20200531-15:45:26.151(0)?   code: 11000,
I20200531-15:45:26.151(0)?   errmsg: 'E11000 duplicate key error collection: meteor.transactions index: txhash_1 dup key: { txhash: "D1DD554F37623AB0A597F1CF1E365A63F048F501D656DDA69A228F0F066C1A51" }',
I20200531-15:45:26.151(0)?   op: {
I20200531-15:45:26.151(0)?     height: 30092,
I20200531-15:45:26.151(0)?     txhash: 'D1DD554F37623AB0A597F1CF1E365A63F048F501D656DDA69A228F0F066C1A51',
I20200531-15:45:26.151(0)?     codespace: 'sdk',
I20200531-15:45:26.151(0)?     code: 11,
I20200531-15:45:26.151(0)?     raw_log: 'out of gas: out of gas in location: WriteFlat; gasWanted: 46082, gasUsed: 47102',
I20200531-15:45:26.151(0)?     gas_wanted: '46082',
I20200531-15:45:26.152(0)?     gas_used: '47102',
I20200531-15:45:26.152(0)?     tx: { type: 'cosmos-sdk/StdTx', value: [Object] },
I20200531-15:45:26.152(0)?     timestamp: '2020-05-31T15:45:16Z',
I20200531-15:45:26.152(0)?     _id: 'MLe2JMgcRiNumwt6j'
I20200531-15:45:26.152(0)?   },
I20200531-15:45:26.152(0)?   name: 'BulkWriteError',
I20200531-15:45:26.152(0)?   driver: true,
I20200531-15:45:26.152(0)?   err: {
I20200531-15:45:26.152(0)?     index: 0,
I20200531-15:45:26.153(0)?     code: 11000,
I20200531-15:45:26.153(0)?     errmsg: 'E11000 duplicate key error collection: meteor.transactions index: txhash_1 dup key: { txhash: "D1DD554F37623AB0A597F1CF1E365A63F048F501D656DDA69A228F0F066C1A51" }',
I20200531-15:45:26.153(0)?     op: {
I20200531-15:45:26.153(0)?       height: 30092,
I20200531-15:45:26.153(0)?       txhash: 'D1DD554F37623AB0A597F1CF1E365A63F048F501D656DDA69A228F0F066C1A51',
I20200531-15:45:26.153(0)?       codespace: 'sdk',
I20200531-15:45:26.153(0)?       code: 11,
I20200531-15:45:26.153(0)?       raw_log: 'out of gas: out of gas in location: WriteFlat; gasWanted: 46082, gasUsed: 47102',
I20200531-15:45:26.153(0)?       gas_wanted: '46082',
I20200531-15:45:26.158(0)?       gas_used: '47102',
I20200531-15:45:26.158(0)?       tx: [Object],
I20200531-15:45:26.158(0)?       timestamp: '2020-05-31T15:45:16Z',
I20200531-15:45:26.158(0)?       _id: 'MLe2JMgcRiNumwt6j'   
I20200531-15:45:26.158(0)?     }
I20200531-15:45:26.159(0)?   },
I20200531-15:45:26.159(0)?   result: BulkWriteResult {
I20200531-15:45:26.159(0)?     result: {
I20200531-15:45:26.159(0)?       ok: 1,
I20200531-15:45:26.159(0)?       writeErrors: [Array],
I20200531-15:45:26.159(0)?       writeConcernErrors: [],
I20200531-15:45:26.159(0)?       insertedIds: [Array],
I20200531-15:45:26.159(0)?       nInserted: 0,
I20200531-15:45:26.159(0)?       nUpserted: 0,
I20200531-15:45:26.159(0)?       nMatched: 0,
I20200531-15:45:26.160(0)?       nModified: 0,
I20200531-15:45:26.160(0)?       nRemoved: 0,
I20200531-15:45:26.160(0)?       upserted: [],
I20200531-15:45:26.160(0)?       lastOp: [Object]
I20200531-15:45:26.160(0)?     }
I20200531-15:45:26.160(0)?   },
I20200531-15:45:26.160(0)?   [Symbol(mongoErrorContextSymbol)]: {}
I20200531-15:45:26.160(0)? }
I20200531-15:45:26.160(0)? Get tx: 19BF02BD7C32FD3955A22AE6DEE94AC039B19DA9E0245EB4C5409B9C47DF8253
I20200531-15:46:07.886(0)?
I20200531-15:46:07.887(0)? <--- Last few GCs --->
I20200531-15:46:07.887(0)?
I20200531-15:46:07.887(0)? [2963:0x335d540] 196517309 ms: Mark-sweep 2016.3 (2052.1) -> 2015.5 (2052.1) MB, 6283.7 / 0.2 ms  (average mu = 0.155, current mu = 0.078) allocation failure scavenge might not succeed
I20200531-15:46:07.887(0)? [2963:0x335d540] 196523729 ms: Mark-sweep 2016.4 (2052.1) -> 2015.6 (2052.1) MB, 6417.5 / 0.2 ms  (average mu = 0.082, current mu = 0.001) allocation failure scavenge might not succeed
I20200531-15:46:07.887(0)?
I20200531-15:46:07.887(0)?
I20200531-15:46:07.888(0)? <--- JS stacktrace --->
I20200531-15:46:07.888(0)?
I20200531-15:46:07.888(0)? ==== JS stack trace =========================================
I20200531-15:46:07.888(0)?
I20200531-15:46:07.888(0)?     0: ExitFrame [pc: 0x13a71b9] 
I20200531-15:46:07.888(0)? Security context: 0x333dc3c808d1 <JSObject>
I20200531-15:46:07.888(0)?     1: added [0x1d89e9a13091] [/home/ubuntu/src/big-dipper/.meteor/local/build/programs/server/packages/ddp-server.js:~378] [pc=0x7dfffbca397](this=0x32673de420e9 <SessionCollectionView map = 0x8e853d36c69>,0x0c349797a679 <String[18]: NNkmHA3jqGtGuYjPH4>,0x2539b74ebdb1 <String[#24]: 5ed3945f9ec5090b93459fe9>,0x0445bcd702f1 <Object map = 0x1344ee019399>)
I20200531-15:46:07.888(0)?     2: ad...
I20200531-15:46:07.888(0)?
W20200531-15:46:07.899(0)? (STDERR) FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
W20200531-15:46:07.899(0)? (STDERR)
W20200531-15:46:07.899(0)? (STDERR) Writing Node.js report to file: report.20200531.154607.2963.0.001.json
W20200531-15:46:07.899(0)? (STDERR) Node.js report completed
W20200531-15:46:07.899(0)? (STDERR)  1: 0x9ef190 node::Abort() [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20200531-15:46:07.899(0)? (STDERR)  2: 0x9f13b2 node::OnFatalError(char const*, char const*) [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20200531-15:46:07.900(0)? (STDERR)  3: 0xb5da9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20200531-15:46:07.900(0)? (STDERR)  4: 0xb5de19 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20200531-15:46:07.900(0)? (STDERR)  5: 0xd0a765  [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20200531-15:46:07.900(0)? (STDERR)  6: 0xd0adf6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20200531-15:46:07.904(0)? (STDERR)  7: 0xd1760a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20200531-15:46:07.904(0)? (STDERR)  8: 0xd18515 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20200531-15:46:07.904(0)? (STDERR)  9: 0xd1afcc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20200531-15:46:07.905(0)? (STDERR) 10: 0xce19bb v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20200531-15:46:07.905(0)? (STDERR) 11: 0x10246ce v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20200531-15:46:07.905(0)? (STDERR) 12: 0x13a71b9  [/home/ubuntu/.meteor/packages/meteor-tool/.1.10.2.121ry7f.gueme++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
=> Exited from signal: SIGABRT
=> Your application is crashing. Waiting for file change.   
```

**To Reproduce**
Not sure how to reproduce it except that it happened when the chain was at ~32,000 blocks (Big Dipper had been running from the genesis block).

This happens everywhere (on all clients I checked, anyways), so I am deleting the sections below on Desktop and Smartphone as I think this is a server issue. 

**Screenshots**

Screenshot of the Meteor process on the server (related to logs above):

<img width="1444" alt="Screen Shot 2020-05-31 at 1 01 33 PM" src="https://user-images.githubusercontent.com/471362/83361607-1ba09f80-a33f-11ea-9b34-aad6869229de.png">

Screenshot of what users see on the browser:

![Screen Shot 2020-05-31 at 1 04 10 PM](https://user-images.githubusercontent.com/471362/83361624-42f76c80-a33f-11ea-8803-e04103420445.png)

Screenshot of the working other instance of Big Dipper on the same chain:

![Screen Shot 2020-05-31 at 1 09 06 PM](https://user-images.githubusercontent.com/471362/83361707-f6f8f780-a33f-11ea-98e8-db34be1dc40e.png)

**Additional context**
I am not certain if I did something wrong here, perhaps. There is plenty of disk space. I have 8 GB of RAM. I have about 180 validators in my chain.

A working URL (at the time of this writing) for Big Dipper (another instance):
```
http://a.explorer.testnet.public.bluzelle.com:3000
```

I killed the meteor process and then restarted it with the same command I always start it with:
```
meteor --settings settings.json
```

It has been running fine for a couple hours now so far. So it would appear the files/database local to Big Dipper are not corrupted in some non-recoverable way.

Thanks.

**Comment by kwunyeung** [comment]
Do you have minting module enabled? It also looks like it's inserting an existing transaction.

**Comment by njmurarka** [comment]
> Do you have minting module enabled? It also looks like it's inserting an existing transaction.

Apologies but do you mean the minting module enabled in our chain? We do not use any minting... so I believe the answer is no. 

In case it is helpful:
```
http://testnet.public.bluzelle.com:1317/genesis.json
```

Still, would this be related to the crash?

**Comment by kwunyeung** [comment]
Tbh, I don't know how your error occur. And it's trying to save a tx that is already in the database.

**Comment by kwunyeung** [comment]
@njmurarka do you still have this problem?

**Comment by njmurarka** [comment]
I have not seen it happen recently. Not sure why.

**Comment by kwunyeung** [comment]
Then can this be closed? You closed and reopened it.

**Comment by njmurarka** [comment]
I did not mean to close it. But I will go ahead and close it. :)

My main challenge right now is getting BD to show the latest TX's, without delay.
