### ISSUE TITLE
missing something for production

### ISSUE THREAD

**Issue by jjhesk** [forbole/big-dipper#365]
looks like missing something to run production

```
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'reify/lib/runtime'
Require stack:
- /www/wwwdp/bundle/programs/server/runtime.js
- /www/wwwdp/bundle/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/www/wwwdp/bundle/programs/server/runtime.js:10:3)
    at Object.<anonymous> (/www/wwwdp/bundle/programs/server/runtime.js:53:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/www/wwwdp/bundle/programs/server/runtime.js',
    '/www/wwwdp/bundle/main.js'
  ]
}
```

```
#!/bin/bash
export MONGO_URL='mongodb://admin:admin@localhost:27017/syncdp'
export ROOT_URL='http://xxx.xxx.io'
export METEOR_SETTINGS=$(jq -c . settings_local.json)
echo $METEOR_SETTINGS
cd /www/wwwdp/bundle/
node main.js

```

**Comment by jjhesk** [comment]
anyone can tell me what am i missing?

**Comment by kwunyeung** [comment]
Did you run `non install` in `bundle/program/server` directory?


https://guide.meteor.com/deployment.html#custom-deployment

**Comment by jjhesk** [comment]
```
> fibers@4.0.3 install /Users/hesk/Documents/ixo/dpexplorer/build/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`darwin-x64-72` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@ install /Users/hesk/Documents/ixo/dpexplorer/build/bundle/programs/server
> node npm-rebuild.js

events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hesk/.npm/_logs/2020-06-19T17_25_40_981Z-debug.log
/Users/hesk/Documents/ixo/dpexplorer/build/bundle/programs/server/node_modules/fibers/fibers.js:90
					return fn.apply(this, arguments);
					          ^

Error: Cannot find module 'meteor-deque'
Require stack:
- /Users/hesk/Documents/ixo/dpexplorer/build/bundle/programs/server/boot.js
- /Users/hesk/Documents/ixo/dpexplorer/build/bundle/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.resolve (internal/modules/cjs/helpers.js:21:19)
    at Object.require (/Users/hesk/Documents/ixo/dpexplorer/build/bundle/programs/server/boot.js:286:34)
    at packages/meteor.js:784:32
    at packages/meteor.js:955:4
    at packages/meteor.js:1508:3
    at /Users/hesk/Documents/ixo/dpexplorer/build/bundle/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /Users/hesk/Documents/ixo/dpexplorer/build/bundle/programs/server/boot.js:226:21
    at /Users/hesk/Documents/ixo/dpexplorer/build/bundle/programs/server/boot.js:464:7

```

**Comment by jjhesk** [comment]
yes. i use npm install and use node -v 12.1.0. now it is not breaking in here.

**Comment by kwunyeung** [comment]
You can refer to [the manual of MongoDB](https://docs.mongodb.com/manual/mongo/#start-the-mongo-shell-and-connect-to-mongodb)

**Comment by kwunyeung** [comment]
@jjhesk I think this issue can be closed.
